import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: './',
  build: {
    rollupOptions: {
      // dev.html is the real Vite entry (dev-mode, loads /src/main.jsx).
      // Tool/index.html is NOT an input — it's an output, regenerated by
      // the postbuild script below. Don't hand-edit Tool/index.html; it
      // gets overwritten on every `npm run build`.
      input: 'dev.html',
      output: {
        entryFileNames: 'assets/index.js',
        chunkFileNames: 'assets/index-[name].js',
        assetFileNames: 'assets/index[extname]',
      },
    },
  },
})
