// TYPES, GROWTH_RATES, PASSIVE_OPTIONS, VARIANT_OPTIONS, INITIAL_POKEMON_DATA, helpers
// Auto-generated from options.generated.js
// Removed fallback re-export for EVOLUTION_ITEM_OPTIONS as ITEM_OPTIONS is now self-contained.


// --- REAL ITEM LIST (NEW) ---
// Categories: held items, evolution stones, TMs, berries, etc.
export const ITEM_OPTIONS = [
  // Held Items
  { value: 'leftovers', label: 'Leftovers' },
  { value: 'choice-scarf', label: 'Choice Scarf' },
  { value: 'life-orb', label: 'Life Orb' },
  { value: 'focus-sash', label: 'Focus Sash' },
  { value: 'expert-belt', label: 'Expert Belt' },
  { value: 'assault-vest', label: 'Assault Vest' },
  { value: 'rocky-helmet', label: 'Rocky Helmet' },
  { value: 'air-balloon', label: 'Air Balloon' },
  { value: 'weakness-policy', label: 'Weakness Policy' },
  { value: 'eviolite', label: 'Eviolite' },
  { value: 'black-sludge', label: 'Black Sludge' },
  { value: 'flame-orb', label: 'Flame Orb' },
  { value: 'toxic-orb', label: 'Toxic Orb' },
  { value: 'mental-herb', label: 'Mental Herb' },
  { value: 'white-herb', label: 'White Herb' },
  { value: 'power-herb', label: 'Power Herb' },
  { value: 'quick-claw', label: 'Quick Claw' },
  { value: 'razor-claw', label: 'Razor Claw' },
  { value: 'razor-fang', label: 'Razor Fang' },
  { value: 'kings-rock', label: 'King’s Rock' },
  { value: 'lagging-tail', label: 'Lagging Tail' },
  { value: 'iron-ball', label: 'Iron Ball' },
  { value: 'macho-brace', label: 'Macho Brace' },
  { value: 'power-bracer', label: 'Power Bracer' },
  { value: 'power-belt', label: 'Power Belt' },
  { value: 'power-lens', label: 'Power Lens' },
  { value: 'power-band', label: 'Power Band' },
  { value: 'power-anklet', label: 'Power Anklet' },
  { value: 'power-weight', label: 'Power Weight' },
  { value: 'destiny-knot', label: 'Destiny Knot' },
  { value: 'smoke-ball', label: 'Smoke Ball' },
  { value: 'shed-shell', label: 'Shed Shell' },
  { value: 'big-root', label: 'Big Root' },
  { value: 'binding-band', label: 'Binding Band' },
  { value: 'absorb-bulb', label: 'Absorb Bulb' },
  { value: 'cell-battery', label: 'Cell Battery' },
  { value: 'luminous-moss', label: 'Luminous Moss' },
  { value: 'snowball', label: 'Snowball' },
  { value: 'eject-button', label: 'Eject Button' },
  { value: 'red-card', label: 'Red Card' },
  { value: 'adrenaline-orb', label: 'Adrenaline Orb' },
  
  // Evolution Stones
  { value: 'fire-stone', label: 'Fire Stone' },
  { value: 'water-stone', label: 'Water Stone' },
  { value: 'thunder-stone', label: 'Thunder Stone' },
  { value: 'leaf-stone', label: 'Leaf Stone' },
  { value: 'moon-stone', label: 'Moon Stone' },
  { value: 'sun-stone', label: 'Sun Stone' },
  { value: 'dusk-stone', label: 'Dusk Stone' },
  { value: 'dawn-stone', label: 'Dawn Stone' },
  { value: 'shiny-stone', label: 'Shiny Stone' },
  { value: 'ice-stone', label: 'Ice Stone' },
  { value: 'oval-stone', label: 'Oval Stone' },
  { value: 'everstone', label: 'Everstone' },
  
  // TMs (Sample)
  { value: 'tm-01', label: 'TM01 (Hone Claws)' },
  { value: 'tm-02', label: 'TM02 (Dragon Claw)' },
  { value: 'tm-03', label: 'TM03 (Psyshock)' },
  { value: 'tm-04', label: 'TM04 (Calm Mind)' },
  { value: 'tm-05', label: 'TM05 (Roar)' },
  { value: 'tm-06', label: 'TM06 (Toxic)' },
  { value: 'tm-07', label: 'TM07 (Hail)' },
  { value: 'tm-08', label: 'TM08 (Bulk Up)' },
  { value: 'tm-09', label: 'TM09 (Venoshock)' },
  { value: 'tm-10', label: 'TM10 (Hidden Power)' },
  
  // Berries
  { value: 'oran-berry', label: 'Oran Berry' },
  { value: 'sitrus-berry', label: 'Sitrus Berry' },
  { value: 'lum-berry', label: 'Lum Berry' },
  { value: 'leppa-berry', label: 'Leppa Berry' },
  { value: 'pecha-berry', label: 'Pecha Berry' },
  { value: 'cheri-berry', label: 'Cheri Berry' },
  { value: 'chesto-berry', label: 'Chesto Berry' },
  { value: 'rawst-berry', label: 'Rawst Berry' },
  { value: 'aspear-berry', label: 'Aspear Berry' },
  { value: 'persim-berry', label: 'Persim Berry' },
  { value: 'wiki-berry', label: 'Wiki Berry' },
  { value: 'figy-berry', label: 'Figy Berry' },
  { value: 'mago-berry', label: 'Mago Berry' },
  { value: 'aguav-berry', label: 'Aguav Berry' },
  { value: 'iapapa-berry', label: 'Iapapa Berry' },
  { value: 'liechi-berry', label: 'Liechi Berry' },
  { value: 'ganlon-berry', label: 'Ganlon Berry' },
  { value: 'salac-berry', label: 'Salac Berry' },
  { value: 'petaya-berry', label: 'Petaya Berry' },
  { value: 'apicot-berry', label: 'Apicot Berry' },
  { value: 'lansat-berry', label: 'Lansat Berry' },
  { value: 'starf-berry', label: 'Starf Berry' },
  { value: 'enigma-berry', label: 'Enigma Berry' },
  { value: 'occa-berry', label: 'Occa Berry' },
  { value: 'passho-berry', label: 'Passho Berry' },
  { value: 'wacan-berry', label: 'Wacan Berry' },
  { value: 'rindo-berry', label: 'Rindo Berry' },
  { value: 'yache-berry', label: 'Yache Berry' },
  { value: 'chople-berry', label: 'Chople Berry' },
  { value: 'kebia-berry', label: 'Kebia Berry' },
  { value: 'shuca-berry', label: 'Shuca Berry' },
  { value: 'coba-berry', label: 'Coba Berry' },
  { value: 'payapa-berry', label: 'Payapa Berry' },
  { value: 'tanga-berry', label: 'Tanga Berry' },
  { value: 'charti-berry', label: 'Charti Berry' },
  { value: 'kasib-berry', label: 'Kasib Berry' },
  { value: 'haban-berry', label: 'Haban Berry' },
  { value: 'colbur-berry', label: 'Colbur Berry' },
  { value: 'babiri-berry', label: 'Babiri Berry' },
  { value: 'chilan-berry', label: 'Chilan Berry' },
  { value: 'roseli-berry', label: 'Roseli Berry' },
  
  // Key Items (Sample)
  { value: 'exp-share', label: 'Exp. Share' },
  { value: 'amulet-coin', label: 'Amulet Coin' },
  { value: 'soothe-bell', label: 'Soothe Bell' },
  { value: 'mental-herb', label: 'Mental Herb' },
  { value: 'choice-band', label: 'Choice Band' },
  { value: 'choice-specs', label: 'Choice Specs' },
  { value: 'focus-band', label: 'Focus Band' },
  { value: 'shell-bell', label: 'Shell Bell' },
  { value: 'wide-lens', label: 'Wide Lens' },
  { value: 'zoom-lens', label: 'Zoom Lens' },
  { value: 'metronome', label: 'Metronome' },
  { value: 'muscle-band', label: 'Muscle Band' },
  { value: 'wise-glasses', label: 'Wise Glasses' },
  { value: 'expert-belt', label: 'Expert Belt' },
  { value: 'light-clay', label: 'Light Clay' },
  { value: 'grip-claw', label: 'Grip Claw' },
  { value: 'damp-rock', label: 'Damp Rock' },
  { value: 'heat-rock', label: 'Heat Rock' },
  { value: 'smooth-rock', label: 'Smooth Rock' },
  { value: 'icy-rock', label: 'Icy Rock' },
  { value: 'terrain-extender', label: 'Terrain Extender' },
  { value: 'protective-pads', label: 'Protective Pads' },
  { value: 'electric-seed', label: 'Electric Seed' },
  { value: 'psychic-seed', label: 'Psychic Seed' },
  { value: 'misty-seed', label: 'Misty Seed' },
  { value: 'grassy-seed', label: 'Grassy Seed' },
];