// Real held-item / modifier type keys, extracted directly from the actual
// `modifierTypeInitObj` object in src/modifier/modifier-type.ts (111 keys,
// confirmed via depth-aware parsing of the real file).
export const HELD_ITEM_OPTIONS = [
  "POKEBALL",
  "GREAT_BALL",
  "ULTRA_BALL",
  "ROGUE_BALL",
  "MASTER_BALL",
  "RARE_CANDY",
  "RARER_CANDY",
  "EVOLUTION_ITEM",
  "RARE_EVOLUTION_ITEM",
  "FORM_CHANGE_ITEM",
  "RARE_FORM_CHANGE_ITEM",
  "EVOLUTION_TRACKER_GIMMIGHOUL",
  "MEGA_BRACELET",
  "DYNAMAX_BAND",
  "TERA_ORB",
  "MAP",
  "POTION",
  "SUPER_POTION",
  "HYPER_POTION",
  "MAX_POTION",
  "FULL_RESTORE",
  "REVIVE",
  "MAX_REVIVE",
  "FULL_HEAL",
  "SACRED_ASH",
  "REVIVER_SEED",
  "WHITE_HERB",
  "ETHER",
  "MAX_ETHER",
  "ELIXIR",
  "MAX_ELIXIR",
  "PP_UP",
  "PP_MAX",
  "SUPER_REPEL",
  "MAX_REPEL",
  "LURE",
  "SUPER_LURE",
  "MAX_LURE",
  "SPECIES_STAT_BOOSTER",
  "RARE_SPECIES_STAT_BOOSTER",
  "TEMP_STAT_STAGE_BOOSTER",
  "DIRE_HIT",
  "BASE_STAT_BOOSTER",
  "ATTACK_TYPE_BOOSTER",
  "MINT",
  "MYSTICAL_ROCK",
  "TERA_SHARD",
  "BERRY",
  "TM_COMMON",
  "TM_GREAT",
  "TM_ULTRA",
  "MEMORY_MUSHROOM",
  "EXP_SHARE",
  "EXP_BALANCE",
  "OVAL_CHARM",
  "EXP_CHARM",
  "SUPER_EXP_CHARM",
  "GOLDEN_EXP_CHARM",
  "LUCKY_EGG",
  "GOLDEN_EGG",
  "SOOTHE_BELL",
  "SCOPE_LENS",
  "LEEK",
  "EVIOLITE",
  "SOUL_DEW",
  "NUGGET",
  "BIG_NUGGET",
  "RELIC_GOLD",
  "AMULET_COIN",
  "GOLDEN_PUNCH",
  "COIN_CASE",
  "LOCK_CAPSULE",
  "GRIP_CLAW",
  "WIDE_LENS",
  "MULTI_LENS",
  "HEALING_CHARM",
  "CANDY_JAR",
  "BERRY_POUCH",
  "FOCUS_BAND",
  "QUICK_CLAW",
  "KINGS_ROCK",
  "LEFTOVERS",
  "SHELL_BELL",
  "TOXIC_ORB",
  "FLAME_ORB",
  "BATON",
  "SHINY_CHARM",
  "ABILITY_CHARM",
  "CATCHING_CHARM",
  "IV_SCANNER",
  "DNA_SPLICERS",
  "MINI_BLACK_HOLE",
  "VOUCHER",
  "VOUCHER_PLUS",
  "VOUCHER_PREMIUM",
  "GOLDEN_POKEBALL",
  "SILVER_POKEBALL",
  "ENEMY_DAMAGE_BOOSTER",
  "ENEMY_DAMAGE_REDUCTION",
  "ENEMY_HEAL",
  "ENEMY_ATTACK_POISON_CHANCE",
  "ENEMY_ATTACK_PARALYZE_CHANCE",
  "ENEMY_ATTACK_BURN_CHANCE",
  "ENEMY_STATUS_EFFECT_HEAL_CHANCE",
  "ENEMY_ENDURE_CHANCE",
  "ENEMY_FUSED_CHANCE",
  "MYSTERY_ENCOUNTER_SHUCKLE_JUICE",
  "MYSTERY_ENCOUNTER_OLD_GATEAU",
  "MYSTERY_ENCOUNTER_BLACK_SLUDGE",
  "MYSTERY_ENCOUNTER_MACHO_BRACE",
  "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET",
]

// Real descriptions extracted directly from pagefaultgames/pokerogue-locales'
// en/modifier-type.json (ModifierType.<KEY>.description). Not all 111 keys
// have a static description in the real game — many common items (Potion,
// Rare Candy, Poke Balls, etc) use a shared, parameterized description class
// at runtime (e.g. "Restores {{restorePoints}} HP") rather than a per-item
// static string, so they're intentionally not included here rather than
// having a fabricated flat description that wouldn't match what the game
// actually shows.
export const HELD_ITEM_DESCRIPTIONS = {
  "EVOLUTION_TRACKER_GIMMIGHOUL": "This Pok\u00e9mon loves treasure! Keep collecting treasure and something might happen!",
  "MEGA_BRACELET": "Mega Stones become available.",
  "DYNAMAX_BAND": "Max Mushrooms become available.",
  "TERA_ORB": "Allows your Pok\u00e9mon to Terastallize. Recharges slowly. Tera Shards also become available.",
  "MAP": "Allows you to choose your destination at a crossroads.",
  "REVIVER_SEED": "Revives the holder for 1/2 HP upon fainting from a direct hit.",
  "WHITE_HERB": "An item to be held by a Pok\u00e9mon. It will restore any lowered stat in battle.",
  "MYSTICAL_ROCK": "Extends the duration of terrain and weather caused by the holder\u2019s moves or Abilities by 2 turns.",
  "MEMORY_MUSHROOM": "Recall one Pok\u00e9mon\u2019s forgotten move.",
  "EXP_SHARE": "Non-participants receive 20% of a single participant\u2019s EXP. Points.",
  "EXP_BALANCE": "Weighs EXP. Points received from battles towards lower-leveled party members.",
  "OVAL_CHARM": "When multiple Pok\u00e9mon participate in a battle, each gets an extra 10% of the total EXP.",
  "SCOPE_LENS": "It\u2019s a lens for scoping out weak points. It boosts the holder\u2019s critical-hit ratio.",
  "LEEK": "This very long and stiff stalk of leek boosts the critical-hit ratio of Farfetch\u2019d\u2019s moves.",
  "EVIOLITE": "This mysterious evolutionary lump boosts the Defense and Sp. Def stats when held by a Pok\u00e9mon that can still evolve.",
  "SOUL_DEW": "Increases the influence of a Pok\u00e9mon\u2019s nature on its stats by 10% (additive).",
  "AMULET_COIN": "Increases money rewards by 20%.",
  "GOLDEN_PUNCH": "Grants 50% of direct damage inflicted as money.",
  "COIN_CASE": "After every 10th battle, receive 10% of your money in interest.",
  "LOCK_CAPSULE": "Allows you to lock item rarities when rerolling items.",
  "HEALING_CHARM": "Increases the effectiveness of HP restoring moves and items by 10% (excludes Revives).",
  "CANDY_JAR": "Increases the number of levels added by Rare Candy items by 1.",
  "BERRY_POUCH": "Adds a 30% chance that a used berry will not be consumed.",
  "FOCUS_BAND": "Adds a 10% chance to survive with 1 HP after being damaged enough to faint.",
  "QUICK_CLAW": "Adds a 10% chance to move first regardless of speed (after priority).",
  "KINGS_ROCK": "Adds a 10% chance an attack move will cause the opponent to flinch.",
  "LEFTOVERS": "Heals 1/16 of a Pok\u00e9mon\u2019s maximum HP every turn.",
  "SHELL_BELL": "Heals 1/8 of a Pok\u00e9mon\u2019s dealt damage.",
  "TOXIC_ORB": "It\u2019s a bizarre orb that exudes toxins when touched and will badly poison the holder during battle.",
  "FLAME_ORB": "It\u2019s a bizarre orb that gives off heat when touched and will affect the holder with a burn during battle.",
  "BATON": "Allows passing along effects when switching Pok\u00e9mon, which also bypasses traps.",
  "SHINY_CHARM": "Dramatically increases the chance of a wild Pok\u00e9mon being Shiny.",
  "ABILITY_CHARM": "Dramatically increases the chance of a wild Pok\u00e9mon having a Hidden Ability.",
  "CATCHING_CHARM": "Increases the chance of getting a critical catch.",
  "IV_SCANNER": "Enables scanning the IVs of wild Pok\u00e9mon.",
  "GOLDEN_POKEBALL": "Adds 1 extra item option at the end of every battle.",
  "ENEMY_DAMAGE_BOOSTER": "Increases damage by 5%.",
  "ENEMY_DAMAGE_REDUCTION": "Reduces incoming damage by 2.5%.",
  "ENEMY_HEAL": "Heals 2% of max HP every turn.",
  "ENEMY_STATUS_EFFECT_HEAL_CHANCE": "Adds a 2.5% chance every turn to heal a status condition.",
  "ENEMY_FUSED_CHANCE": "Adds a 1% chance that a wild Pok\u00e9mon will be a fusion.",
  "MYSTERY_ENCOUNTER_OLD_GATEAU": "Increases some of the holder\u2019s stats.",
  "MYSTERY_ENCOUNTER_BLACK_SLUDGE": "The stench is so powerful that shops will only sell you items at a steep cost increase.",
  "MYSTERY_ENCOUNTER_MACHO_BRACE": "Defeating a Pok\u00e9mon grants the holder a stack of it. Each stack boosts stats a bit. Bonus at max stacks.",
  "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": "Imbues the owner with luck to find Bug Type Pok\u00e9mon more often. Has a strange heft to it.",
}

// Real Nature enum values, confirmed against src/enums/nature.ts directly.
export const NATURE_OPTIONS = [
  "HARDY",
  "LONELY",
  "BRAVE",
  "ADAMANT",
  "NAUGHTY",
  "BOLD",
  "DOCILE",
  "RELAXED",
  "IMPISH",
  "LAX",
  "TIMID",
  "HASTY",
  "SERIOUS",
  "JOLLY",
  "NAIVE",
  "MODEST",
  "MILD",
  "QUIET",
  "BASHFUL",
  "RASH",
  "CALM",
  "GENTLE",
  "SASSY",
  "CAREFUL",
  "QUIRKY",
]

// Real evolution item display names, from pokerogue-locales
// en/modifier-type.json (ModifierType.EvolutionItem.<KEY>). The real locale
// only has display names for these, no separate per-item effect text.
export const EVOLUTION_ITEM_DESCRIPTIONS = {
  "NONE": "None",
  "LINKING_CORD": "Linking Cord",
  "SUN_STONE": "Sun Stone",
  "MOON_STONE": "Moon Stone",
  "LEAF_STONE": "Leaf Stone",
  "FIRE_STONE": "Fire Stone",
  "WATER_STONE": "Water Stone",
  "THUNDER_STONE": "Thunder Stone",
  "ICE_STONE": "Ice Stone",
  "DUSK_STONE": "Dusk Stone",
  "DAWN_STONE": "Dawn Stone",
  "SHINY_STONE": "Shiny Stone",
  "CRACKED_POT": "Cracked Pot",
  "SWEET_APPLE": "Sweet Apple",
  "TART_APPLE": "Tart Apple",
  "STRAWBERRY_SWEET": "Strawberry Sweet",
  "UNREMARKABLE_TEACUP": "Unremarkable Teacup",
  "UPGRADE": "Upgrade",
  "DUBIOUS_DISC": "Dubious Disc",
  "DRAGON_SCALE": "Dragon Scale",
  "PRISM_SCALE": "Prism Scale",
  "RAZOR_CLAW": "Razor Claw",
  "RAZOR_FANG": "Razor Fang",
  "OVAL_STONE": "Oval Stone",
  "REAPER_CLOTH": "Reaper Cloth",
  "ELECTIRIZER": "Electirizer",
  "MAGMARIZER": "Magmarizer",
  "PROTECTOR": "Protector",
  "SACHET": "Sachet",
  "WHIPPED_DREAM": "Whipped Dream",
  "SYRUPY_APPLE": "Syrupy Apple",
  "CHIPPED_POT": "Chipped Pot",
  "GALARICA_CUFF": "Galarica Cuff",
  "GALARICA_WREATH": "Galarica Wreath",
  "AUSPICIOUS_ARMOR": "Auspicious Armor",
  "MALICIOUS_ARMOR": "Malicious Armor",
  "MASTERPIECE_TEACUP": "Masterpiece Teacup",
  "SUN_FLUTE": "Sun Flute",
  "MOON_FLUTE": "Moon Flute",
  "BLACK_AUGURITE": "Black Augurite",
  "PEAT_BLOCK": "Peat Block",
  "METAL_ALLOY": "Metal Alloy",
  "SCROLL_OF_DARKNESS": "Scroll Of Darkness",
  "SCROLL_OF_WATERS": "Scroll Of Waters",
  "LEADERS_CREST": "Leader\u2019s Crest",
}
